@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.connorrowe.igneoussmithy.setup;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;